### ISSUE TITLE
Make the login page responsive

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#12]

**Comment by Laxmankohar** [comment]
Hey @AtriSukul1508 , I would like to work on this issue under JWOC. Can you assign it to me?

**Comment by AtriSukul1508** [comment]
Assigned @Laxmankohar

**Comment by Laxmankohar** [comment]
@AtriSukul1508 , Can you please check it?

![image](https://user-images.githubusercontent.com/73365025/219848850-992c36cf-e1a0-4862-b54c-368d4ea67539.png)
![image](https://user-images.githubusercontent.com/73365025/219848852-87e5938d-7238-42c2-8d91-b2635b22aac7.png)

**Comment by AtriSukul1508** [comment]
@Laxmankohar Reduce the font size of the "login to your account" heading in the first picture a little bit, and everything will be fine

**Comment by Laxmankohar** [comment]
ok

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/219849673-da3d8df7-b6a4-4da7-a62a-262f3b5bb1aa.png)

**Comment by AtriSukul1508** [comment]
yeah it's good

**Comment by Laxmankohar** [comment]
so, I am going to make a pull request.

**Comment by AtriSukul1508** [comment]
ok
