### ISSUE TITLE
[GSSOC'23] Google, Facebook and Github Authentication Not working

### ISSUE THREAD

**Issue by MuzmmilKhan1** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#122]
Hello,
          Hope you are doing well. I was going through your website and I noticed that Google, Facebook, and GitHub authentication are not working. And no Functionality was added for this: 

https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/77438943/77ce0fd9-aba4-4758-81e5-605fb2992f91

Please Assign this issue to me. So, I can add this functionality.
Thank you.

**Comment by AtriSukul1508** [comment]
@MuzmmilKhan1 go ahead, make sure to fetch the repo before making a pr

**Comment by AtriSukul1508** [comment]
@MuzmmilKhan1 what's the update ?

**Comment by Maryann-01** [comment]
@AtriSukul1508 ,can this be assigned to me please?
