### ISSUE TITLE
Implement lazy loading

### ISSUE THREAD

**Issue by sumitkr2000** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#138]
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

- `Reduced initial load time`

- `Improved user experience`

- `More responsive website`

- `Increased SEO ranking`

**Comment by AtriSukul1508** [comment]
@sumitkr2000  go ahead, before creating a pr make sure to fetch the repo

**Comment by sumitkr2000** [comment]
> @sumitkr2000 go ahead, before creating a pr make sure to fetch the repo

yeah sure!
