### ISSUE TITLE
Inserting link

### ISSUE THREAD

**Issue by utkarsh006** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#14]
- Want to add contributing guidelines link to the main readme.
- It was not done previously bcz then the link would open in my cloned version of the repository.
- You can give me other documentation tasks if you feel this task is easy and too short.
- Kindly assign me this issue under JWOC.

**Comment by AtriSukul1508** [comment]
Assigned @utkarsh006, add some screenshots of the website
