### ISSUE TITLE
Add Captcha verification

### ISSUE THREAD

**Issue by Manice18** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#154]
To prevent bots and to differentiate between real users, I want to add captcha verification in the sign up page.

**Comment by AtriSukul1508** [comment]
@Manice18 go ahead,

**Comment by AtriSukul1508** [comment]
@Manice18 any updates?

**Comment by Manice18** [comment]
@AtriSukul1508 yeh almost done, will update you tomorrow

**Comment by Manice18** [comment]
@AtriSukul1508  i am unassigning myself because i came up with some imp work for a hackathon
You can assign this issue to someone else who wants to do it
