### ISSUE TITLE
Add reset password/forgot password API functionality

### ISSUE THREAD

**Issue by Jennifer-tech** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#169]
No reset password/forgot password Api functionality is present, making the forgot password in the UI not work. When a user enters their email, the API does not provide any feedback like sending a message to the current user's email. As a contributor at GSSOC'23, I would like to address this issue to ensure an amazing user experience of the app

**Comment by Jennifer-tech** [comment]
@AtriSukul1508, please assign this issue to me

**Comment by Jennifer-tech** [comment]
Thank you @AtriSukul1508

**Comment by AtriSukul1508** [comment]
@Jennifer-tech any updates ?

**Comment by Jennifer-tech** [comment]
Hi @AtriSukul1508, I am done with the task and would want to create a PR but I am seeing just the master branch. Should I create a PR for the master branch?

**Comment by AtriSukul1508** [comment]
@Jennifer-tech yes
