### ISSUE TITLE
Make the signup page responsive

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#17]

**Comment by Laxmankohar** [comment]
Hey @AtriSukul1508 , I would like to work on this issue under JWOC. Can you assign it to me?

**Comment by AtriSukul1508** [comment]
Go ahead @Laxmankohar

**Comment by Laxmankohar** [comment]
@AtriSukul1508 , Have a  look.

![image](https://user-images.githubusercontent.com/73365025/219864319-86884f1c-1cbe-4248-b098-b4927e472438.png)
![image](https://user-images.githubusercontent.com/73365025/219864365-6f6b90f5-62c4-4f36-956e-5f7cc9717585.png)

**Comment by AtriSukul1508** [comment]
Add some merging at the top and bottom and in the first picture reduce the height of each input box and the signup button a little bit

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/219866886-3b5d443d-baa8-447e-aa19-5e9630fe9105.png)
![image](https://user-images.githubusercontent.com/73365025/219866892-c4f44f90-3ad2-4ddf-aa6c-32d06158f893.png)

**Comment by AtriSukul1508** [comment]
good
