### ISSUE TITLE
Add "Login with Google" and |"Login with Facebook" Functionality

### ISSUE THREAD

**Issue by Maryann-01** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#170]
I noticed that when a user clicks on the Google or Facebook icon to login with Google or Facebook, nothing happens.
I will like to add this functionality to enable users login with their google and facebook account.

**Comment by Maryann-01** [comment]
@AtriSukul1508,please assign this issue to me under gssoc'23

**Comment by Maryann-01** [comment]
Hello @AtriSukul1508 ,please assign this to me

**Comment by AtriSukul1508** [comment]
@Maryann-01 go ahead, It would be great if you could add facebook as well

**Comment by AtriSukul1508** [comment]
@Maryann-01 Make sure to fetch the repo before making a pr

**Comment by Maryann-01** [comment]
Okay,I would do that.Thank you.

**Comment by Maryann-01** [comment]
@AtriSukul1508 ,
![Screenshot (182)](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/89715739/b3c15ff3-e22e-4b2c-8332-3922606aa621)
This is the image I am seeing anytime I run the app,it is entirely different(the UI) from what is on the vercel live link and even the facebook and google icons are not there.Please check and which one am I to work with?
This is what is displaying on the homepage for the livelink ,
![Screenshot (183)](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/89715739/a9af8c07-2b85-44da-8005-286f14333b24)

**Comment by AtriSukul1508** [comment]
@Maryann-01 It should look exactly like the one in the vercel link. If the problem persists, fork the repo once again and try checking again.

**Comment by Maryann-01** [comment]
@AtriSukul1508 ,I created a pull request.Please review.

**Comment by Maryann-01** [comment]
@AtriSukul1508 ,Please review My PR.
