### ISSUE TITLE
Change in ui

### ISSUE THREAD

**Issue by NomikaGajula** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#175]
I want to change the ui of login page to make it look cool
Please assign me this @AtriSukul1508 under GSSOC'23

**Comment by AtriSukul1508** [comment]
@NomikaGajula go ahead

**Comment by NomikaGajula** [comment]
Greeting of the day!

Thank you for assigning it to me. I am facing an error while running the
app can you please help me out.
when i run the command npm start then it says that start is not found what
to do but in json file the start command is written in scripts
so please help me out what to do
will be waiting for your reply
Thank you!

Regards
Nomika Gajula

**Comment by AtriSukul1508** [comment]
@NomikaGajula have you installed all the necessary packages ?

**Comment by NomikaGajula** [comment]
Yes, I did. I have installed all the necessary packages
