### ISSUE TITLE
Create a user profile page that opens when a user clicks on their profile picture

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#18]

**Comment by Laxmankohar** [comment]
Hey @AtriSukul1508 , I would like to  work on this issue under JWOC. Can you assign it to me?

**Comment by VaibhavTalkhande** [comment]
I would like to work on this issue under JWOC. Can you assign it to me?

**Comment by AtriSukul1508** [comment]
@Laxmankohar  Since you are already working on an issue, i cannot assign you

**Comment by AtriSukul1508** [comment]
@VaibhavTalkhande Assigned, while creating a PR, make sure to attach a screenshot and maintain the current color combination

**Comment by VaibhavTalkhande** [comment]
@AtriSukul1508 ok i will do it

**Comment by VaibhavTalkhande** [comment]
i am not able to run this project on my machine . you can assign it other person.
sorry for inconvenience.

**Comment by AtriSukul1508** [comment]
@Laxmankohar you can now work on that

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/220668458-943f8fed-44ff-47b1-a430-d5d1cf268226.png)


@AtriSukul1508 , I think i have to set profile picture on profile icon on the navbar beside logout button.

**Comment by AtriSukul1508** [comment]
@Laxmankohar any updates?

**Comment by Laxmankohar** [comment]
@AtriSukul1508 , I am getting this error, how can i resolve it?
![image](https://user-images.githubusercontent.com/73365025/223023574-c9e329fd-5825-4051-a0ef-163ae05c14fa.png)

**Comment by AtriSukul1508** [comment]
@Laxmankohar Yeah but you can just use a placeholder values for now, i will implement the signup functionality later

**Comment by Laxmankohar** [comment]
> @Laxmankohar Yeah but you can just use placeholder values for now, i will implement the signup functionality later

I am not getting. Can you please elaborate a little more.

**Comment by AtriSukul1508** [comment]
@Laxmankohar just create a static page, i will add the required infos of the user later

**Comment by Laxmankohar** [comment]
> @Laxmankohar just create a static page, i will add the required infos of the user later

@AtriSukul1508 , like this?

![image](https://user-images.githubusercontent.com/73365025/223307883-540b6456-d62b-495a-be71-709be0ef87e0.png)

**Comment by AtriSukul1508** [comment]
Yeah

**Comment by Laxmankohar** [comment]
when i click on the profile of user in the navbar,profile component render but the content inside profile page is not displaying, what would be the reason?

![image](https://user-images.githubusercontent.com/73365025/223667526-607f3c05-117a-48c6-89a8-a14e5b34c858.png)

**Comment by Laxmankohar** [comment]
@AtriSukul1508 bro, please check and confirm it.
https://user-images.githubusercontent.com/73365025/223692336-0fdb6935-427f-44b8-a023-bd05ad98bc9c.mp4

**Comment by AtriSukul1508** [comment]
Hey, @Laxmankohar There's just a box popping up

**Comment by Laxmankohar** [comment]
> Hey, @Laxmankohar There's just a box popping up

yes, What you need then?

**Comment by AtriSukul1508** [comment]
@Laxmankohar , There should be an entire page, doesn't need to contain a lot of complex functionality, but a decent one would be fine since there is no authentication at the moment, just use placeholder values for username, email, etc.

**Comment by Laxmankohar** [comment]
So, should i  kept the popping box or not?

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/223821041-f615e38f-2fb4-443d-8e36-4b70e717e5e7.png)

**Comment by AtriSukul1508** [comment]
@Laxmankohar example website - https://dribbble.com/shots/17219796-My-details-settings-page-Untitled-UI

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/223951659-039e6c87-1fa9-4c62-9f73-e874fbc6365f.png)

**Comment by Laxmankohar** [comment]
[React App - Google Chrome 2023-03-09 15-08-07.zip](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/files/10929935/React.App.-.Google.Chrome.2023-03-09.15-08-07.zip)

**Comment by AtriSukul1508** [comment]
Nice, make sure you fetch the repo before making the PR

**Comment by Laxmankohar** [comment]
Ok.
