### ISSUE TITLE
[Request]: Convert .png, jpeg Images File Format into webp File Format🌟🌟

### ISSUE THREAD

**Issue by NarendraKoya999** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#186]
### Purpose of Raising this Issue
- **WebP is a modern image format that provides superior lossless and lossy compression for images on the web. Using WebP, webmasters and web developers can create smaller, richer images that make the web faster. WebP lossless images are 26% smaller in size compared to PNGs.**
- **I have taken PNG File in your Project Directory. Observe in Screenshot, It's almost 57% of File Size Reduced.**
- **So, I work on those Changes Entire Project Directory.**

### Proof of My Issue
![turing-1](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/84512164/f8492805-7125-4f7b-8e8e-cdc8d701b4e2)

**Comment by AtriSukul1508** [comment]
@NarendraKoya999 go ahead
