### ISSUE TITLE
Adding unit test cases using Jest Testing Library

### ISSUE THREAD

**Issue by Jagroop2000** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#2]
**Subject:** Request for Jest integration in ReactJS projects on GitHub
**Hi there !!**

I am writing to request the **integration of Jest**, a popular JavaScript testing library, into your project that uses ReactJS. This would allow developers to write and run unit tests for their React components directly on the platform. Jest's simplicity and power would greatly improve the development experience and increase the reliability of code.

And the good thing is Jest testing files wouldn't add any memory consumption to the project when we make a build or it is on production.
Please add **hard level** label to this or you can decide it while merging or reviewing PR request.
Thank you for considering this request. I look forward to your response.

Best regards,
Jagroop

**Comment by himanshu1221** [comment]
Can i work on this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me
