### ISSUE TITLE
Add a preloader

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#26]
The preloader should convey a clear description of the website

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC

**Comment by AtriSukul1508** [comment]
@Hritik1503 Go ahead

**Comment by AtriSukul1508** [comment]
@Hritik1503 any updates?

**Comment by AtriSukul1508** [comment]
@vk20july Go for it

**Comment by pooranjoyb** [comment]
Assign me this issue under JWOC 2023. @AtriSukul1508

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
