### ISSUE TITLE
[Update] : Improve hover effect in footer Media icons

### ISSUE THREAD

**Issue by AbhiPatel10** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#39]
We Should improve Hover effect in Media icons.

on hover media icon we need to make cursor to pointer

![image](https://user-images.githubusercontent.com/76242769/223102949-dca4465b-23b1-4b11-bf1f-4c778288363b.png)

Please assign this issue to me under JWOC

**Comment by AtriSukul1508** [comment]
@AbhiPatel10 go ahead
