### ISSUE TITLE
Redesign the navbar

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#5]

**Comment by tanvirraihanislam** [comment]
Hi @AtriSukul1508 I would like to work on this issue, can you please assign this to me?

**Comment by AtriSukul1508** [comment]
Hello @tanvirraihanislam, I cannot assign the issue to you now because the contribution period has not started. Also, any comments made before 12:00 AM , February 15th will not be taken into consideration. So , please post your comment after 12:00 AM, then i will assign the issue to you

**Comment by tanvirraihanislam** [comment]
Sure @AtriSukul1508, I will post my comment after 12a.m. on the 15th of February. Thank you for the reciprocation.

**Comment by Awesomeasma** [comment]
I want to work on this issue under JWOC

**Comment by Sarita-021** [comment]
hi @AtriSukul1508 
I am interested to work on it. 
I have made projects and have an experience in designing different nav bars.
Can you assign it to me .  under JWOC

**Comment by AtriSukul1508** [comment]
go ahead @Awesomeasma and while creating a Pull Request, please attach a screenshot

**Comment by Awesomeasma** [comment]
okay..thank you.

**Comment by Sanjay-Narkedamilli** [comment]
can i work on this??

**Comment by Awesomeasma** [comment]
> go ahead @Awesomeasma and while creating a Pull Request, please attach a screenshot

@AtriSukul1508 Could you elaborate what your expectations are on this issue ?

**Comment by mecivil** [comment]
I want to contribute to this issue under JWOC

**Comment by AtriSukul1508** [comment]
@Awesomeasma, Remove the user name section and only use an icon for the search, make the search bar entirely visible only on hover, the rest is up to you and use the same color combination

**Comment by AtriSukul1508** [comment]
@Awesomeasma any updates?

**Comment by AtriSukul1508** [comment]
@Awesomeasma Since you haven't responded and it's been more than a day, I'm unassigning you.

**Comment by AtriSukul1508** [comment]
@Sarita-021 go ahead

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by Sarita-021** [comment]
@AtriSukul1508 I am not familiar with react so you can assign it to anyone else.

**Comment by AtriSukul1508** [comment]
@mecivil now you can work on the issue
