### ISSUE TITLE
Sign up page link is broken 

### ISSUE THREAD

**Issue by karthiknadar1204** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#54]
The user is not redirected to the main page after signing up

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Uma-Shankar0927** [comment]
Hello, @AtriSukul1508 I would like to work on this project. I can fix the described issue. Please assign me the task.

**Comment by aniket2125ec1117** [comment]
are you using jwt for authentication if yes then i can solve this error
