### ISSUE TITLE
CORS problem in signup page and validation in form

### ISSUE THREAD

**Issue by tushar-glitch** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#55]
There is a cors problem in the backend by which the signup page is not working. I can fix this issue in the backend and also put validations in both the front and backend for proper functioning. You can assign this issue to me under GSSOC'23

**Comment by AtriSukul1508** [comment]
@tushar-glitch , go ahead

**Comment by AtriSukul1508** [comment]
@tushar-glitch any updates ?
