### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#56]
I would like to improve the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by AtriSukul1508** [comment]
Go ahead @harshsingh32

**Comment by mahekkg** [comment]
@AtriSukul1508 I would like to assist on the same.
Have already made a successful contribution regarding READme.md file.
Let me know your views.
