### ISSUE TITLE
Create a footer section

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#6]

**Comment by Suniti-0020** [comment]
Hi @AtriSukul1508 
I am interested to work on the issue.  under JWOC

**Comment by PARASnagpal99** [comment]
I would like to work on this . Please assign this to me .

**Comment by AtriSukul1508** [comment]
go ahead @PARASnagpal99 ,  while creating a pull request , make sure to attach a screenshot

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by AtriSukul1508** [comment]
@PARASnagpal99 any updates?

**Comment by AtriSukul1508** [comment]
@ManasaKaza you can now work on that issue

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by AtriSukul1508** [comment]
@TuhinBanerjee31 you can now work on that
