### ISSUE TITLE
Bug in sign up page

### ISSUE THREAD

**Issue by sumitkr2000** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#65]
Hey, @AtriSukul1508 There is a bug in the signup page as I am unable to sign up. Please assign me this issue so that I can fix it. Thank you.

**Comment by aditya9277** [comment]
I can solve this issue very fast, i have already analyzed the code, please assign me this issue @AtriSukul1508

**Comment by aniket2125ec1117** [comment]
i can solve this issue please assign this issue to me
