### ISSUE TITLE
New feature: add login with google option

### ISSUE THREAD

**Issue by bhaskarkumar1** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#66]
Please assign me the task to add login/signup option with google option via choosing google account.
![googlelogin](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/84345649/50c5233a-0332-4fc8-a30b-2343ff75a8f1)

**Comment by AtriSukul1508** [comment]
Go ahead @bhaskarkumar1 , make sure to fetch the repo before making a PR

**Comment by bhaskarkumar1** [comment]
thank you @AtriSukul1508, for asssigning this task  I will work  on it.

**Comment by AtriSukul1508** [comment]
@bhaskarkumar1 what's the update?

**Comment by agarwalhimanshugaya** [comment]
anyone not working on this issue please assign me this issue i want to work in this issue

**Comment by Maryann-01** [comment]
@AtriSukul1508 ,please assign it to me.I will update you on my progress every 2weeks.I already created an issue on it,#170.Here is the link,https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/issues/170
