### ISSUE TITLE
Update OTP authentication during Sign Up

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#67]
It doesn't have otp authentication during Sign up. It will be better if this feature is added. 
Assign me this issue to solve under GSSoC contributor.

**Comment by AtriSukul1508** [comment]
Go ahead @Rupantar-Borphukan, make sure you fetch the repo before making a PR

**Comment by Rupantar-Borphukan** [comment]
> Go ahead @Rupantar-Borphukan, make sure you fetch the repo before making a PR

ok
