### ISSUE TITLE
[FEAT] Custom Error Page 404

### ISSUE THREAD

**Issue by virajchandra51** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#68]
I will design an Error Page for calls or redirecting to pages which do not exist.

Hello!
I am Viraj Chandra, a proud contributor at GSSoC '23. I would like to the contribute to this project by designing an Error Page for calls or redirecting to pages which do not exist.

Things I will be doing as of now:
- [ ]  Designing the error page 404

@AtriSukul1508  Please Assign me this.

**Comment by AtriSukul1508** [comment]
@virajchandra51 assigned, make sure to fetch the repo before making a PR

**Comment by PatilHarshh** [comment]
@AtriSukul1508 i also want to add 404 error page

**Comment by PatilHarshh** [comment]
hey @AtriSukul1508 may i proceed , will complete asap !!

**Comment by AtriSukul1508** [comment]
@PatilHarshh you can now work on that issue, change the color combination. Follow the current color combination of the website
