### ISSUE TITLE
Improve UI: Sign in page

### ISSUE THREAD

**Issue by rishuraj1** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#69]
I believe the sign in page needs a revamp, we might want to improve the look and design for better user experience.

![Screenshot (93)](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/47839626/a216148d-ac1c-4e05-a8b0-652593594c7f)

Can you assign me this task  under GSSoC' 23 ? Thank You!

**Comment by aasthaaaa7** [comment]
please assign me this task under GSSOC'23

**Comment by AtriSukul1508** [comment]
@rishuraj1 assigned, make sure to fetch the repo before making a PR

**Comment by rishuraj1** [comment]
@AtriSukul1508  okay. Thanks!
