### ISSUE TITLE
Enhance the UI of the homepage

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#7]

**Comment by Suniti-0020** [comment]
Hi @AtriSukul1508 I am interested in the issue , can you assign it to me . under JWOC

**Comment by SasiVardhan247** [comment]
I want to work on this issue under JWOC,assign this to me

**Comment by AtriSukul1508** [comment]
go ahead @Suniti-0020 , while creating a pull request, make sure to attach a screenshot

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by AtriSukul1508** [comment]
@Suniti-0020 any updates?

**Comment by Suniti-0020** [comment]
@AtriSukul1508 I will need 1 more day

**Comment by Suniti-0020** [comment]
@AtriSukul1508  I have lost my complete data from my pc I will not be able to cope up with it more , you can assign to others . Sorry , for the inconveniences caused by me.....

**Comment by AtriSukul1508** [comment]
@SasiVardhan247 you can now work on that

**Comment by AtriSukul1508** [comment]
@SasiVardhan247 any updates ?

**Comment by SasiVardhan247** [comment]
I'm unable make it .can you assign to someone

**Comment by neokd** [comment]
I would like to work on this issue under JWOC

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by AtriSukul1508** [comment]
@neokd you can now work on that

**Comment by neokd** [comment]
Thanks

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC
