### ISSUE TITLE
feat: password visibility toggle in signup

### ISSUE THREAD

**Issue by SINJINI-G** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#71]
Toggle the visibility of the password in user login page on button click.
Can I work on this issue for gssoc? 

## After change
![image](https://github.com/AtriSukul1508/Njack_Hack_It_Out-Tur1ng-/assets/98143022/6eef4f59-8b34-4552-af27-359d6a2214f7)

**Comment by AtriSukul1508** [comment]
Assigned @SINJINI-G, make sure to fetch the repo before making a pr
