### ISSUE TITLE
Design a logo for the website

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#8]
The logo should convey a clear description of the website

**Comment by bcsamrudh** [comment]
Hey, I would like to contribute to this.
Please assign me this issue,so that I can start working on it as soon as possible!
OPEN SOURCE PROGRAM: JWOC23

**Comment by AtriSukul1508** [comment]
Go ahead @bcsamrudh , while creating a PR make sure to attach a screenshot

**Comment by bcsamrudh** [comment]
When should it be submitted.

**Comment by AtriSukul1508** [comment]
1 day for Easy level issue

**Comment by Gun2902** [comment]
can u assign me

**Comment by AtriSukul1508** [comment]
@bcsamrudh any updates ?

**Comment by AtriSukul1508** [comment]
@Gun2902 you can work on that

**Comment by Gun2902** [comment]
konse folder m dalna h

**Comment by AtriSukul1508** [comment]
tur1ng/src/Assets/

**Comment by Gun2902** [comment]
last conformation logo design tool se hi banna h na lyah html or css

**Comment by AtriSukul1508** [comment]
@Gun2902 The design tool will be more helpful i guess, or whatever you want, store the logo in PNG format
