### ISSUE TITLE
Enhance the UI of the Write blog page

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#9]

**Comment by Tushar-go** [comment]
hey! i want to work on this issue under jwoc

**Comment by Laxmankohar** [comment]
Hey @AtriSukul1508 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by AtriSukul1508** [comment]
Assigned @Tushar-go, make sure to attach a screenshot while creating a PR and maintain the current color combination

**Comment by AtriSukul1508** [comment]
@Tushar-go any updates?
